/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-04-24 08:19:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nimbusds.jose.util.Base64URL;
import com.nimbusds.jose.util.Base64;
import sami.lineworks.testap.common.Constants;
import sami.lineworks.testap.common.Utils;
import net.minidev.json.JSONArray;
import net.minidev.json.JSONObject;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/jsp/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String serverToken = Constants.getServerToken();
	JSONArray botList = null;
	if (Utils.isEmpty(serverToken)) {
		serverToken = "未取得です";
	} else {
		Utils.setBotList();
		botList = Utils.getBotList();
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<title>Developer管理画面(BOT管理)</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a href=\"http://127.0.0.1:8080/app/jsp/org.jsp\">組織管理</a> ｜\r\n");
      out.write("\t<a href=\"http://127.0.0.1:8080/app/jsp/admin.jsp\">BOT管理</a>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<h1>Developer 管理画面(BOT管理)</h1>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<h2>サーバ情報</h2>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li>サーバ名：");
      out.print(Constants.SERVER_NAME);
      out.write("</li>\r\n");
      out.write("\t\t<li>サーバID：");
      out.print(Constants.SERVER_ID);
      out.write("</li>\r\n");
      out.write("\t\t<li>サーバトークン：");
      out.print(serverToken);
      out.write("</li>\r\n");
      out.write("\t\t<li style=\"list-style: none\">\r\n");
      out.write("\t\t\t<form method=\"get\" action=\"/app/getServerToken\">\r\n");
      out.write("\t\t\t\t<button type='submit' name='action'>サーバトークン更新</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<h2>BOT管理</h2>\r\n");
      out.write("\t<h3>BOT一覧</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/registBot\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t");

				if (null != botList) {
					for (int i = 0; i < botList.size(); i++) {
						JSONObject jsonObject = (JSONObject) botList.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><img border=\"0\"\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(jsonObject.get("photoUrl"));
      out.write("\" width=\"32\" height=\"32\">\r\n");
      out.write("\t\t\t\t[botNo]");
      out.print(jsonObject.get("botNo"));
      out.write("，[name]");
      out.print(jsonObject.get("name"));
      out.write("，[status]");
      out.print(jsonObject.get("status"));
      out.write("</li>\r\n");
      out.write("\t\t\t");

				}
				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<li>botはまだ登録されていません。</li>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t<li>新規登録する</li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[name] <input type=\"text\" size=\"50\"\r\n");
      out.write("\t\t\t\tname=\"name\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[photoUrl] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"photoUrl\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>新規Bot登録</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>ドメイン登録</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/registBot2Domain\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[botNo] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"10\" name=\"botNo\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>ドメイン登録</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>メッセージ受信サーバ登録</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/setCallback\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[botNo] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"10\" name=\"botNo\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[callbackUrl] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"callbackUrl\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type=\"submit\" name=\"action\">メッセージ受信サーバ登録</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>メッセージ送信テスト</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/sndBotMsg\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[botNo] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"10\" name=\"botNo\"></input>，[accountId] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"10\" name=\"accountId\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[message]<input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"message\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type=\"submit\" name=\"action\">メッセージ送信テスト</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>csvファイルからメッセージ送信テスト</h3>\r\n");
      out.write("\t<form method=\"POST\" enctype=\"multipart/form-data\"\r\n");
      out.write("\t\taction=\"/app/sndBotMsgFromCsv\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[csv file] <input type=\"file\"\r\n");
      out.write("\t\t\t\tname=\"upfile\"><br />\r\n");
      out.write("\t\t\t<br /></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type=\"submit\" name=\"action\">メッセージ送信(from\r\n");
      out.write("\t\t\t\t\tcsv)テスト</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t<h3>LINE 連携 ON</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/enableLine\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\" name=\"obj\">{}</textarea></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type=\"submit\" name=\"action\">連携ON</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t<h3>ドメインチェック</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/checkDomain\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\" name=\"obj\">{}</textarea></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type=\"submit\" name=\"action\">Check</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
