/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-05-18 01:22:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nimbusds.jose.util.Base64URL;
import com.nimbusds.jose.util.Base64;
import sami.lineworks.testap.common.Constants;
import sami.lineworks.testap.common.Utils;
import net.minidev.json.JSONArray;
import net.minidev.json.JSONObject;

public final class org_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/jsp/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String serverToken = Constants.getServerToken();
	String result = (String) request.getAttribute("result");
	String subMail = (String) request.getAttribute("subMail");
	String contact = (String) request.getAttribute("contact");
	String level = (String) request.getAttribute("level");
	if (Utils.isEmpty(serverToken)) {
		serverToken = "未取得です";
	}
	if (Utils.isEmpty(result)) {
		result = "未取得です";
	}
	if (Utils.isEmpty(subMail)) {
		subMail = "未取得です";
	}
	if (Utils.isEmpty(contact)) {
		contact = "未取得です";
	}
	if (Utils.isEmpty(level)) {
		level = "-";
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<title>Developer管理画面(組織管理)</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a href=\"http://127.0.0.1:8080/app/jsp/org.jsp\">組織管理</a> ｜\r\n");
      out.write("\t<a href=\"http://127.0.0.1:8080/app/jsp/admin.jsp\">BOT管理</a>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<h1>Developer 管理画面(組織管理)</h1>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<h2>サーバ情報</h2>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li>サーバ名：");
      out.print(Constants.SERVER_NAME);
      out.write("</li>\r\n");
      out.write("\t\t<li>サーバID：");
      out.print(Constants.SERVER_ID);
      out.write("</li>\r\n");
      out.write("\t\t<li>サーバトークン：");
      out.print(serverToken);
      out.write("</li>\r\n");
      out.write("\t\t<li style=\"list-style: none\">\r\n");
      out.write("\t\t\t<form method=\"get\" action=\"/app/getServerToken\">\r\n");
      out.write("\t\t\t\t<button type='submit' name='action'>サーバトークン更新</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<h2>組織管理</h2>\r\n");
      out.write("\t<h3>組織追加</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/registOrg\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\" name=\"obj\"></textarea></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>新規組織登録</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>組織修正</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/updateOrg\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\" name=\"obj\"></textarea></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>組織情報修正</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>組織削除</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/deleteOrg\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>組織削除</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>組織照会</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/getOrg\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>組織照会</button></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\" name=\"obj\">");
      out.print(result);
      out.write("</textarea></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>組織移動</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/moveOrg\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\" name=\"obj\"></textarea></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>組織移動</button></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>組織のサブメールアドレス追加</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/registSubMail\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[email] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"email\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>サブメールアドレス登録</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>組織のサブメールアドレス照会</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/getSubMail\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>サブメールアドレス照会</button></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\">");
      out.print(subMail);
      out.write("</textarea></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>組織のサブメールアドレス削除</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/deleteSubMail\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[exKey] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"exKey\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[email] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"email\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>サブメールアドレス削除</button></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>アカウント情報照会</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/getContact\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[account] <input type=\"text\"\r\n");
      out.write("\t\t\t\tsize=\"50\" name=\"account\"></input></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>アカウント情報照会</button></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[JSON]<br /> <textarea rows=\"10\"\r\n");
      out.write("\t\t\t\t\tcols=\"100\">");
      out.print(contact);
      out.write("</textarea></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<h3>職級追加</h3>\r\n");
      out.write("\t<form method=\"post\" action=\"/app/addLevels\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[Request]<br /> <textarea\r\n");
      out.write("\t\t\t\t\trows=\"10\" cols=\"100\" name=\"obj\"></textarea></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\"><button type='submit' name='action'>職級追加</button></li>\r\n");
      out.write("\t\t\t<li style=\"list-style: none\">[Response]<br /> <textarea\r\n");
      out.write("\t\t\t\t\trows=\"10\" cols=\"100\">");
      out.print(level);
      out.write("</textarea></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
